import {installTestOrganModuleResolution} from "../helpers/organ-module-resolution";
import { randomUUID } from "node:crypto";
import { readFileSync } from "node:fs";
import { mkdtemp,rm } from "node:fs/promises";
import path from "node:path";
import { tmpdir } from "node:os";
import { createClient,type SupabaseClient } from "@supabase/supabase-js";
import { beforeAll,beforeEach,afterEach,afterAll,describe,it,expect,vi } from "vitest";
import * as children from "node:child_process";
import * as media from "../../lib/medical-motion/composition/ffmpeg-runtime";
import * as organs from "../../lib/medical-motion/organ-modules";
import { withTestCacheAnatomy } from "../helpers/cache-anatomy-fixture";
import { compositionRuntime } from "../helpers/composition-media";
import { deliverySchema } from "../helpers/medical-motion-delivery";
import { testHealth } from "../helpers/approved-personalization";
import { cleanupArtifactOwner } from "../helpers/medical-motion-artifacts";
import { contextContent } from "../helpers/medical-motion-context";
import { client } from "../helpers/medical-motion-rpc";
import { sql } from "../helpers/medical-motion-postgres";
import { MedicalMotionJobRepository } from "../../lib/medical-motion/job.repository";
import { createMedicalMotionArtifactRuntime } from "../../lib/medical-motion/artifacts/runtime";
import { SupabasePrivateArtifactStorage,MEDICAL_MOTION_BUCKET,type PrivateArtifactStorage } from "../../lib/medical-motion/artifacts/storage";
import { TrustedPersonalizationProducer } from "../../lib/medical-motion/composition/producer";
import { MedicalMotionDeliveryService } from "../../lib/medical-motion/delivery/service";
import { ApprovedPersonalizationRepository } from "../../lib/medical-motion/composition/approved-spec.repository";
import { CompositionMetrics } from "../../lib/medical-motion/composition/metrics";
import { handleDeliveryApi } from "../../lib/medical-motion/delivery/api";
import { authenticateApiRequest } from "../../lib/api/api-auth";
import { createCompositionJobRuntime } from "../../lib/medical-motion/composition/job-runtime";
import { MedicalMotionCompositionService } from "../../lib/medical-motion/composition/service";
import { productSchema,grantTestMotion } from "../helpers/product-entitlements";
vi.mock("node:child_process",async original=>{const actual=await original<typeof children>();return {...actual,spawn:vi.fn(actual.spawn)};});
const nativeFetch=globalThis.fetch.bind(globalThis), target=new URL(process.env.NEXT_PUBLIC_SUPABASE_URL!);
const prodLine=readFileSync(".env.local","utf8").split(/\r?\n/).find(v=>v.startsWith("NEXT_PUBLIC_SUPABASE_URL="));
const prod=new URL(prodLine!.slice(prodLine!.indexOf("=")+1).trim().replace(/^["']|["']$/g,""));
if(target.protocol!=="https:"||target.hostname!=="pmjuyyqofkdbgqmrdbuh.supabase.co"||target.hostname===prod.hostname||target.port||target.username||target.password||target.search||target.hash)throw Error("ISOLATED_PROVIDER_GUARD_FAILED");
const safeFetch:typeof fetch=async(input,init)=>{const u=new URL(typeof input==="string"?input:input instanceof URL?input.href:input.url);
 if(u.protocol!=="https:"||u.hostname!==target.hostname||u.port||u.username||u.password)throw Error("ISOLATED_PROVIDER_GUARD_FAILED");
 try{return await nativeFetch(input,{...init,redirect:"error",signal:init?.signal??AbortSignal.timeout(20000)});}catch{throw Error("ISOLATED_PROVIDER_REQUEST_FAILED");}};
const make=(key:string)=>createClient(target.href,key,{auth:{persistSession:false,autoRefreshToken:false,detectSessionInUrl:false},global:{fetch:safeFetch}});
const admin=make(process.env.SUPABASE_SERVICE_ROLE_KEY!);
describe("real isolated authenticated patient delivery / durable media",()=>{
 const users:{id:string;token:string;session:SupabaseClient}[]=[],objects=new Set<string>(),pending=new Set<string>();let root:string;
 beforeAll(async()=>{await productSchema();const bucket=await admin.storage.getBucket(MEDICAL_MOTION_BUCKET);expect(!bucket.error&&bucket.data?.public===false).toBe(true);
  for(let i=0;i<2;i++){const email=`delivery-${randomUUID()}@example.test`,password=randomUUID()+randomUUID();const r=await admin.auth.admin.createUser({email,password,email_confirm:true});if(r.error||!r.data.user)throw Error("SYNTHETIC_AUTH_CREATE_FAILED");
   const session=make(process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY!);users.push({id:r.data.user.id,token:"",session});const login=await session.auth.signInWithPassword({email,password});if(login.error||!login.data.session)throw Error("SYNTHETIC_AUTH_LOGIN_FAILED");users.at(-1)!.token=login.data.session.access_token;}
 },60000);
 beforeEach(async()=>{if(pending.size)throw Error("AMBIGUOUS_TEST_RESOURCE_PRESERVED");vi.stubGlobal("fetch",safeFetch);for(const u of users){await sql(`insert into auth.users(id) values('${u.id}');`);await grantTestMotion(u.id);}
  root=await mkdtemp(path.join(tmpdir(),"organheal-delivery-test-"));vi.stubEnv("MEDICAL_MOTION_OUTPUT_ROOT",path.join(root,"render-output"));vi.stubEnv("MEDICAL_MOTION_RENDER_SCRIPT",path.resolve("tests/fixtures/medical-motion-handler-smoke.py"));installTestOrganModuleResolution(withTestCacheAnatomy()).legacy;});
 afterEach(async()=>{if(pending.size)throw Error("AMBIGUOUS_TEST_RESOURCE_PRESERVED");for(const id of objects){const r=await admin.storage.from(MEDICAL_MOTION_BUCKET).remove([id]);if(r.error||await new SupabasePrivateArtifactStorage(admin).read(id))throw Error("EXACT_TEST_STORAGE_CLEANUP_FAILED");}objects.clear();
  vi.restoreAllMocks();vi.unstubAllGlobals();vi.unstubAllEnvs();for(const u of [...users].reverse())await cleanupArtifactOwner(u.id);
  if(path.dirname(root)===tmpdir()&&path.basename(root).startsWith("organheal-delivery-test-"))await rm(root,{recursive:true,force:true});});
 afterAll(async()=>{for(const u of users){const out=await u.session.auth.signOut({scope:"global"});if(out.error)throw Error("SYNTHETIC_SESSION_REVOKE_FAILED");const r=await admin.auth.admin.deleteUser(u.id);if(r.error)throw Error("SYNTHETIC_AUTH_CLEANUP_FAILED");}},60000);
 const signal=()=>new AbortController().signal;
 async function setup(){const stored=new SupabasePrivateArtifactStorage(admin);const storage:PrivateArtifactStorage={read:(id,s)=>stored.read(id,s),put:async(id,bytes,mime)=>{pending.add(id);await stored.put(id,bytes,mime);pending.delete(id);objects.add(id);}};
  const transport={rpc:(name:string,args:Record<string,unknown>)=>client.rpc(name,args),storage:admin.storage} as unknown as SupabaseClient, runtime=await compositionRuntime(root),metrics=new CompositionMetrics();
  const producer=new TrustedPersonalizationProducer(transport,async owner=>testHealth(owner,owner===users[0].id?42:73),"development",storage,runtime);
  let delivery:MedicalMotionDeliveryService;
  const worker=createMedicalMotionArtifactRuntime(transport,{mode:"development",reuse:true,observeReuse:metrics.reuse,composition:{runtime,concurrency:1},advanceDelivery:()=>delivery.advancePending(signal())},storage);
  delivery=new MedicalMotionDeliveryService(transport,worker.artifacts,"development",producer);
  const deps={authenticate:authenticateApiRequest,service:()=>delivery};
  async function invoke(user:number,action:"create"|"status"|"cancel"|"access"|"history",id?:string,language:"ar"|"en"="ar"){
   const r=new Request("https://organheal.test/api/medical-motion/requests",{method:action==="create"||action==="cancel"?"POST":"GET",headers:{Authorization:`Bearer ${users[user].token}`},...(action==="create"?{body:JSON.stringify({sourceRef:users[user].id,sceneIndex:0,language,aspectRatio:"16:9"})}:{})});return handleDeliveryApi(r,action,id,deps);}
  async function queue(user=0,language:"ar"|"en"="ar"){await new MedicalMotionJobRepository(client).enqueue(users[user].id,users[user].id,contextContent(),0);const r=await invoke(user,"create",undefined,language);expect(r.status).toBe(202);return (await r.json()).request as {requestId:string;status:string};}
  async function finish(id:string,user=0){for(let i=0;i<8;i++){const r=await delivery.status(users[user].id,id);if(r.status==="ready")return r;await worker.worker.processNext();}throw Error("TEST_REQUEST_NOT_READY");}
  return {delivery,worker,invoke,queue,finish,storage,runtime,transport,metrics,producer};
 }
 it("authenticated A ready/private access; B cannot status/cancel/access; double-click reuses request",async()=>{const p=await setup(),a=await p.queue();const duplicate=await p.queue();expect(duplicate.requestId).toBe(a.requestId);const ready=await p.finish(a.requestId);
  expect(ready.status).toBe("ready");expect(ready.artifact?.language).toBe("ar");for(const action of ["status","cancel","access"] as const)expect((await p.invoke(1,action,a.requestId)).status).toBe(404);
  const access=await p.invoke(0,"access",a.requestId);expect(access.status).toBe(200);const signed=await access.json();expect(signed.expiresInSeconds).toBe(60);const bytes=await safeFetch(signed.url);expect(bytes.status).toBe(200);expect((await bytes.arrayBuffer()).byteLength>0).toBe(true);
  const ordinary=await users[1].session.storage.from(MEDICAL_MOTION_BUCKET).download(ready.artifact!.artifactId);expect(Boolean(ordinary.error)).toBe(true);
  const hidden=await p.invoke(0,"status",a.requestId);const publicRow=(await hidden.json()).request;expect(Object.keys(publicRow).some(k=>/job|lease|token|context|source|spec|key/i.test(k))).toBe(false);
 },120000);
 it("cross-user base hit preserves distinct private ar/en finals and repeat avoids Blender/FFmpeg",async()=>{const p=await setup(),a=await p.queue(),ar=await p.finish(a.requestId),b=await p.queue(1,"en"),en=await p.finish(b.requestId,1);
  const aa=await p.delivery.repository.read(users[0].id,a.requestId),bb=await p.delivery.repository.read(users[1].id,b.requestId);const specs=new ApprovedPersonalizationRepository(p.transport),as=await specs.read(aa.specId!,users[0].id),bs=await specs.read(bb.specId!,users[1].id);
  expect(as.baseArtifactId===bs.baseArtifactId).toBe(true);expect(ar.artifact!.artifactId===en.artifact!.artifactId).toBe(false);expect(p.metrics.snapshot).toMatchObject({"base-cache-miss":1,"base-cache-hit":1});
  const calls=vi.mocked(children.spawn).mock.calls,blender=calls.filter(c=>String(c[0]).toLowerCase().includes("blender"));expect(blender.length).toBe(1);const count=calls.filter(c=>String(c[0]).endsWith("ffmpeg.exe")&&(c[1] as string[]).at(-1)==="personalized.mp4").length;expect(count).toBe(2);
  const repeated=await p.queue();expect(repeated.requestId).toBe(a.requestId);expect(await p.worker.worker.processNext()).toBe(false);expect(p.worker.composition!.metrics().executions).toBe(2);
 },120000);
 it("queued cancellation remains durable and worker produces no private final",async()=>{const p=await setup(),a=await p.queue();expect((await p.invoke(0,"cancel",a.requestId)).status).toBe(200);await p.worker.worker.processNext();await p.worker.worker.processNext();expect((await p.delivery.status(users[0].id,a.requestId)).status).toBe("cancelled");expect(await sql(`select count(*) from public.medical_motion_approved_specs where user_id='${users[0].id}';`)).toBe("0");},120000);
 it("cancel one owner while another needs the shared base preserves that owner's final",async()=>{const p=await setup(),a=await p.queue(),b=await p.queue(1,"en");await p.delivery.cancel(users[0].id,a.requestId);const ready=await p.finish(b.requestId,1);expect(ready.status).toBe("ready");expect((await p.delivery.status(users[0].id,a.requestId)).status).toBe("cancelled");},120000);
 it("cancellation during actual FFmpeg prevents final publication",async()=>{const p=await setup(),a=await p.queue();await p.worker.worker.processNext();await p.delivery.advancePending(signal());const row=await p.delivery.repository.read(users[0].id,a.requestId),spec=await new ApprovedPersonalizationRepository(p.transport).read(row.specId!,users[0].id);
  let enter!:()=>void;const entered=new Promise<void>(resolve=>{enter=resolve}),actual=media.executeMediaProcess;
  vi.spyOn(media,"executeMediaProcess").mockImplementation(async(config,exe,args,cwd,abort)=>{if(exe==="ffmpeg"&&args.at(-1)==="personalized.mp4"){enter();return actual(config,exe,["-nostdin","-hide_banner","-loglevel","error","-re","-f","lavfi","-i","color=s=64x64:r=24:d=30","-f","null","-"],cwd,abort);}return actual(config,exe,args,cwd,abort);});
  const task=p.worker.composition!.processById(spec.jobId);await entered;await p.delivery.cancel(users[0].id,a.requestId);await task;expect((await p.delivery.status(users[0].id,a.requestId)).status).toBe("cancelled");expect(await sql(`select count(*) from public.background_job_results where job_id='${spec.jobId}';`)).toBe("0");},120000);
 it("completion winning cancellation preserves ready artifact and exact private identity",async()=>{const p=await setup(),a=await p.queue(),before=await p.finish(a.requestId);const after=await p.delivery.cancel(users[0].id,a.requestId);expect(after.status).toBe("ready");expect(after.artifact!.artifactId===before.artifact!.artifactId).toBe(true);},120000);
 it("expired signed transport is denied and owner reissues without recomposition",async()=>{const p=await setup(),a=await p.queue();await p.finish(a.requestId);const first=await p.delivery.access(users[0].id,a.requestId);expect((await safeFetch(first.url)).ok).toBe(true);
  await new Promise(resolve=>setTimeout(resolve,66000));expect((await safeFetch(first.url)).ok).toBe(false);const next=await p.delivery.access(users[0].id,a.requestId);expect((await safeFetch(next.url)).ok).toBe(true);expect(first.artifact.artifactId===next.artifact.artifactId).toBe(true);expect(p.worker.composition!.metrics().executions).toBe(1);
 },150000);
 it("publication interruption/retry remains one stable product request and original spec",async()=>{const p=await setup(),a=await p.queue();await p.worker.worker.processNext();await p.delivery.advancePending(signal());const row=await p.delivery.repository.read(users[0].id,a.requestId),s=await new ApprovedPersonalizationRepository(p.transport).read(row.specId!,users[0].id);let fail=true;
  const interrupted={...p.transport,rpc:async(name:string,args:Record<string,unknown>)=>{if(name==="publish_background_job_result"&&fail)throw Error("TEST_RESPONSE_LOSS");return client.rpc(name,args);}} as unknown as SupabaseClient;
  const jobs=createCompositionJobRuntime(interrupted,new MedicalMotionCompositionService(interrupted,p.worker.artifacts,p.storage,p.runtime,"development"),{concurrency:1,signal:signal()});await jobs.processById(s.jobId);expect((await p.delivery.status(users[0].id,a.requestId)).status).toBe("preparing");
  fail=false;await sql(`update public.background_jobs set available_at=clock_timestamp() where id='${s.jobId}';`);await jobs.processById(s.jobId);expect((await p.delivery.status(users[0].id,a.requestId)).status).toBe("ready");expect((await p.queue()).requestId).toBe(a.requestId);
 },120000);
 it("cancel winning atomic approval creates no orphan spec or composition job",async()=>{const p=await setup(),a=await p.queue();await p.worker.worker.processNext();
  let enter!:()=>void,release!:()=>void;const entered=new Promise<void>(r=>{enter=r}),held=new Promise<void>(r=>{release=r}),actual=p.producer.approve.bind(p.producer);
  vi.spyOn(p.producer,"approve").mockImplementation(async(...args)=>{const spec=await actual(...args);enter();await held;return spec;});
  const advance=p.delivery.advancePending(signal());await entered;await p.delivery.cancel(users[0].id,a.requestId);release();await advance;
  expect((await p.delivery.status(users[0].id,a.requestId)).status).toBe("cancelled");expect(await sql(`select count(*) from public.medical_motion_approved_specs where user_id='${users[0].id}';`)).toBe("0");
 },120000);
 it("cancel winning the publication race fences the uploaded final from delivery",async()=>{const p=await setup(),a=await p.queue();await p.worker.worker.processNext();await p.delivery.advancePending(signal());
  const direct=client as unknown as {rpc(name:string,args:Record<string,unknown>):Promise<{data:unknown;error:unknown}>};
  let enter!:()=>void,release!:()=>void;const entered=new Promise<void>(r=>{enter=r}),held=new Promise<void>(r=>{release=r}),actual=direct.rpc;
  vi.spyOn(direct,"rpc").mockImplementation(async(name,args)=>{if(name==="publish_background_job_result"){enter();await held;}return actual(name,args);});
  const task=p.worker.worker.processNext();await entered;await p.delivery.cancel(users[0].id,a.requestId);release();await task;
  expect((await p.delivery.status(users[0].id,a.requestId)).status).toBe("cancelled");expect((await p.invoke(0,"access",a.requestId)).status).toBe(409);
  const raw=await p.delivery.repository.read(users[0].id,a.requestId),spec=await new ApprovedPersonalizationRepository(p.transport).read(raw.specId!,users[0].id);expect(await sql(`select count(*) from public.background_job_results where job_id='${spec.jobId}';`)).toBe("0");
 },120000);
 it("current production medical gate returns product unavailable without private approval",async()=>{const p=await setup();await new MedicalMotionJobRepository(client).enqueue(users[0].id,users[0].id,contextContent(),0);
  const production=new MedicalMotionDeliveryService(p.transport,p.worker.artifacts,"production");const req=new Request("https://organheal.test/api/medical-motion/requests",{method:"POST",headers:{Authorization:`Bearer ${users[0].token}`},body:JSON.stringify({sourceRef:users[0].id,sceneIndex:0,language:"ar",aspectRatio:"16:9"})});
  const response=await handleDeliveryApi(req,"create",undefined,{authenticate:authenticateApiRequest,service:()=>production});expect(response.status).toBe(202);const row=(await response.json()).request;
  expect(row.status).toBe("failed");expect(row.failureCode).toBe("medical-visualization-not-available");expect(await sql(`select count(*) from public.medical_motion_approved_specs where user_id='${users[0].id}';`)).toBe("0");
 },120000);
});
