import { describe,it,expect } from "vitest";
import { ALERT_CODES,WorkerOperationalAlerts,WorkerRestartBudget,serviceOperationalState,type OperationalAlert } from "@/lib/medical-motion/worker/operations";

describe("isolated worker operational alert policy",()=>{
  function harness(){let time=0;const alerts:OperationalAlert[]=[];const policy=new WorkerOperationalAlerts(alert=>alerts.push(alert),()=>time);return {policy,alerts,advance:(ms:number)=>{time+=ms;}};}
  it("100 repeated poll failures emit one critical alert within cooldown",()=>{const h=harness();for(let i=0;i<100;i++)h.policy.observe({event:"POLL_FAILED"});expect(h.alerts).toHaveLength(1);expect(h.alerts[0]).toMatchObject({severity:"CRITICAL",code:ALERT_CODES.DATABASE,count:3});});
  it("100 repeated recovery failures emit one critical alert",()=>{const h=harness();for(let i=0;i<100;i++)h.policy.observe({event:"RECOVERY_FAILED"});expect(h.alerts).toHaveLength(1);expect(h.alerts[0].code).toBe(ALERT_CODES.RECOVERY);});
  it("cooldown expiry re-emits with a bounded suppression count",()=>{const h=harness();h.policy.emit(ALERT_CODES.DATABASE,"CRITICAL");for(let i=0;i<99;i++)h.policy.emit(ALERT_CODES.DATABASE,"CRITICAL");h.advance(60000);h.policy.emit(ALERT_CODES.DATABASE,"CRITICAL");expect(h.alerts).toHaveLength(2);expect(h.alerts[1].suppressed).toBe(99);});
  it("arbitrary input fields cannot enter alerts",()=>{const h=harness();h.policy.observe({event:"READY",workerId:"invalid secret",clinicalMessage:"PRIVATE",plan:"PRIVATE",diagnosis:"PRIVATE",localPath:"PRIVATE",url:"PRIVATE",password:"PRIVATE",stdout:"PRIVATE"});expect(JSON.stringify(h.alerts)).not.toContain("PRIVATE");expect(h.alerts[0].workerId).toBeUndefined();});
  it("allows only a UUID worker identifier",()=>{const h=harness();const id="00000000-0000-4000-8000-000000000001";h.policy.observe({event:"READY",workerId:id});expect(h.alerts[0].workerId).toBe(id);});
  it.each([[64,ALERT_CODES.CONFIG],[69,ALERT_CODES.BLENDER],[75,ALERT_CODES.DATABASE],[76,ALERT_CODES.STORAGE],[78,ALERT_CODES.DISK],[70,ALERT_CODES.PACKAGE]] as const)("classifies startup exit %s",(code,expected)=>{const h=harness();h.policy.startupFailure(code);expect(h.alerts[0]).toMatchObject({code:expected,severity:"CRITICAL"});});
  it("repeated job retry warns only after three occurrences",()=>{const h=harness();h.policy.observe({event:"JOB_FINISHED",disposition:"retry"});h.policy.observe({event:"JOB_FINISHED",disposition:"retry"});expect(h.alerts).toHaveLength(0);h.policy.observe({event:"JOB_FINISHED",disposition:"retry"});expect(h.alerts[0].code).toBe(ALERT_CODES.RETRY);});
  it("does not warn for successful or ownership-lost job dispositions",()=>{const h=harness();for(let i=0;i<100;i++){h.policy.observe({event:"JOB_FINISHED",disposition:"complete"});h.policy.observe({event:"JOB_FINISHED",disposition:"ownership-lost"});}expect(h.alerts).toHaveLength(0);});
  it("warns for a durable publication reconciliation without record contents",()=>{const h=harness();h.policy.observe({event:"PUBLICATION_RECONCILED",artifact:"PRIVATE"});expect(h.alerts[0].code).toBe(ALERT_CODES.RECONCILE);expect(JSON.stringify(h.alerts)).not.toContain("PRIVATE");});
  it("warns after sixty seconds of degraded health",()=>{const h=harness();const state={phase:"degraded" as const,ready:false,recoveryComplete:true,activeJobCount:0};h.policy.health(state);h.advance(59999);h.policy.health(state);expect(h.alerts).toHaveLength(0);h.advance(1);h.policy.health(state);expect(h.alerts[0].code).toBe(ALERT_CODES.DEGRADED);});
  it("ready health resets degraded duration",()=>{const h=harness();const state={phase:"degraded" as const,ready:false,recoveryComplete:true,activeJobCount:0};h.policy.health(state);h.advance(50000);h.policy.health({...state,phase:"ready",ready:true});h.advance(20000);h.policy.health(state);expect(h.alerts).toHaveLength(0);});
  it("warns when health responses cease",()=>{const h=harness();h.policy.health({phase:"ready",ready:true,recoveryComplete:true,activeJobCount:0});h.advance(15000);h.policy.tick({});expect(h.alerts[0].code).toBe(ALERT_CODES.HEALTH);});
  it("warns on low disk reserve and old waiting work with counts only",()=>{const h=harness();h.policy.tick({freeBytes:127,diskFloorBytes:128,oldestWaitingMs:120000,waitingCount:2});expect(h.alerts.map(alert=>alert.code)).toEqual([ALERT_CODES.DISK,ALERT_CODES.WAITING]);expect(h.alerts[1].count).toBe(2);});
  it("a failed sink does not throw into ownership",()=>{const policy=new WorkerOperationalAlerts(()=>{throw Error("private");});expect(()=>policy.emit(ALERT_CODES.READY,"INFO")).not.toThrow();});
  it("limits a global sixty-second alert window to twenty emits",()=>{const h=harness();for(const code of Object.values(ALERT_CODES))h.policy.emit(code,"WARNING");expect(h.alerts.length).toBeLessThanOrEqual(20);});
  it("unknown event names and codes do not enter the sink",()=>{const h=harness();h.policy.observe({event:"PRIVATE"});h.policy.emit("PRIVATE" as typeof ALERT_CODES.READY,"INFO");expect(h.alerts).toHaveLength(0);});
});
describe("persistable bounded service restart policy",()=>{
  it("three restarts use 1/2/4 second delays then refuse a fourth",()=>{const budget=new WorkerRestartBudget([],()=>10000);expect([budget.reserve(),budget.reserve(),budget.reserve(),budget.reserve()]).toEqual([1000,2000,4000,undefined]);});
  it("persists the budget across supervisor restart",()=>{const first=new WorkerRestartBudget([],()=>10000);first.reserve();const second=new WorkerRestartBudget(first.snapshot(),()=>11000);expect(second.reserve()).toBe(2000);});
  it("expires attempts only after ten minutes",()=>{let now=0;const budget=new WorkerRestartBudget([],()=>now);budget.reserve();budget.reserve();budget.reserve();now=599999;expect(budget.reserve()).toBeUndefined();now=600000;expect(budget.reserve()).toBe(1000);});
  it.each([null,{},[1,2,3,4],[-1],[NaN],[20000]])("corrupt restart state fails closed",saved=>{expect(()=>new WorkerRestartBudget(saved,()=>10000)).toThrow("INVALID_RESTART_STATE");});
  it("SCM running alone never means worker ready",()=>{expect(serviceOperationalState(true)).toBe("starting");expect(serviceOperationalState(true,{phase:"starting",ready:false,recoveryComplete:false,activeJobCount:0})).toBe("starting");});
  it("requires readiness and completed recovery",()=>{const state={phase:"ready" as const,ready:true,recoveryComplete:false,activeJobCount:0};expect(serviceOperationalState(true,state)).not.toBe("ready");expect(serviceOperationalState(true,{...state,recoveryComplete:true})).toBe("ready");expect(serviceOperationalState(false,{...state,recoveryComplete:true})).toBe("stopped");});
});
