"use client";

import Link from "next/link";

import { useAdminLanguage } from "@/app/admin/use-admin-language";

import "./editorial-policy.css";

// Describes how content is made and what the site does not claim. It makes no
// statement about anyone's qualifications: an article names its medical
// reviewer on the article itself, and only when one really reviewed it.
export default function EditorialPolicyPage() {
  const { isArabic, language, text } = useAdminLanguage();

  const sections: { title: string; body: string[] }[] = [
    {
      title: text("What we publish", "ما الذي ننشره"),
      body: [
        text(
          "OrganHeal AI publishes educational health information in English and Arabic: explanations of lab results, common conditions, and questions to ask a doctor.",
          "ينشر OrganHeal AI معلومات صحية تثقيفية بالعربية والإنجليزية: شرح نتائج التحاليل والحالات الشائعة وأسئلة يمكنك طرحها على طبيبك."
        ),
        text(
          "It is not a diagnosis, a treatment plan, or a substitute for a licensed clinician.",
          "وهي ليست تشخيصاً ولا خطة علاج ولا بديلاً عن الطبيب المرخّص."
        ),
      ],
    },
    {
      title: text("Where the information comes from", "من أين تأتي المعلومات"),
      body: [
        text(
          "We base articles on recognised public-health and medical bodies, such as the World Health Organization, national health agencies, and established medical societies and hospitals. Articles list their sources at the bottom when they have been recorded.",
          "نبني المقالات على جهات صحية وطبية معروفة مثل منظمة الصحة العالمية والهيئات الصحية الوطنية والجمعيات الطبية والمستشفيات المعروفة. وتُذكر المصادر أسفل المقال متى سُجّلت."
        ),
        text(
          "The videos we show are published by the organisations named beside each one and are embedded, not copied.",
          "الفيديوهات التي نعرضها تنشرها الجهات المذكورة بجانب كل فيديو، وهي مضمّنة وليست منسوخة."
        ),
      ],
    },
    {
      title: text("Medical review", "المراجعة الطبية"),
      body: [
        text(
          "An article that has been reviewed by a clinician shows the reviewer's name and the review date at its foot. If an article does not show that line, it has not been medically reviewed yet, and you should treat it as general education.",
          "المقال الذي راجعه طبيب أو مختص يعرض اسم المراجع وتاريخ المراجعة أسفله. وإن لم يظهر هذا السطر فالمقال لم يُراجَع طبياً بعد، فتعامل معه على أنه تثقيف عام."
        ),
      ],
    },
    {
      title: text("How AI is used", "كيف نستخدم الذكاء الاصطناعي"),
      body: [
        text(
          "The assistant and the video explainers are generated by AI. They can make mistakes. They are designed not to diagnose, not to recommend medicines or doses, and to direct urgent symptoms to emergency care.",
          "المساعد والفيديوهات الشارحة يولّدها الذكاء الاصطناعي، وقد يخطئ. وهي مصمّمة لألا تشخّص ولا توصي بأدوية أو جرعات، وأن توجّه الأعراض العاجلة إلى الرعاية الطارئة."
        ),
        text(
          "When you ask about your own report, your text is sent securely to our AI provider to produce the answer.",
          "وعندما تسأل عن تقريرك الخاص يُرسل نصّه بأمان إلى مزوّد الذكاء الاصطناعي لتوليد الإجابة."
        ),
      ],
    },
    {
      title: text("Corrections", "التصحيحات"),
      body: [
        text(
          "If you think something is wrong or out of date, tell us and we will review it and correct it.",
          "إذا رأيت أن معلومة خاطئة أو قديمة فأخبرنا وسنراجعها ونصحّحها."
        ),
      ],
    },
  ];

  return (
    <main className="ohPageShell editorialPolicy" dir={isArabic ? "rtl" : "ltr"} lang={language}>
      <header>
        <p className="ohEyebrow">{text("Trust", "الثقة")}</p>
        <h1>{text("Editorial & medical review policy", "سياسة التحرير والمراجعة الطبية")}</h1>
        <p>
          {text(
            "What you can rely on here, and what you should not.",
            "ما يمكنك الاعتماد عليه هنا، وما لا ينبغي أن تعتمد عليه."
          )}
        </p>
      </header>

      {sections.map((section) => (
        <section key={section.title} className="editorialPolicyBlock">
          <h2>{section.title}</h2>
          {section.body.map((paragraph) => (
            <p key={paragraph}>{paragraph}</p>
          ))}
        </section>
      ))}

      <p className="editorialPolicyLinks">
        <Link href="/contact">{text("Report a correction", "أبلغ عن تصحيح")}</Link>
        {" · "}
        <Link href="/medical-disclaimer">{text("Medical disclaimer", "إخلاء المسؤولية الطبي")}</Link>
        {" · "}
        <Link href="/privacy">{text("Privacy", "الخصوصية")}</Link>
      </p>
    </main>
  );
}
