import {
  buildHypothesisCandidates,
  runHypothesisReasoningPipeline,
} from "../evidence-backed-reasoning";

import type {
  HypothesisGenerationContext,
  HypothesisReasoningPipelineResult,
} from "../evidence-backed-reasoning";

import {
  runGenerationRegistry,
} from "./registry";

import type {
  HypothesisGenerationRegistryResult,
} from "./registry";

export type RegistryHypothesisReasoningResult = {
  /*
   * Complete execution provenance from the central registry.
   */
  registry:
    HypothesisGenerationRegistryResult;

  /*
   * Evaluation, ranking, and leading interpretation produced
   * from the candidates generated by the registry.
   */
  pipeline:
    HypothesisReasoningPipelineResult;
};

/*
 * Runs the registered hypothesis generators and forwards their
 * generated candidates into the evidence-backed reasoning
 * pipeline.
 *
 * This adapter preserves the separation between:
 *
 * - generator registration and execution
 * - candidate normalization
 * - candidate evaluation
 * - hypothesis ranking
 * - leading-interpretation selection
 */
export function runRegisteredHypothesisReasoning(
  context: HypothesisGenerationContext
): RegistryHypothesisReasoningResult {
  const registry =
    runGenerationRegistry(context);

  const candidates =
    buildHypothesisCandidates(
      registry.generatedCandidates
    );

  const pipeline =
    runHypothesisReasoningPipeline(
      candidates,
      context.hypothesisGate
    );

  return {
    registry,
    pipeline,
  };
}