import type { AnatomyAssessment, AnatomyLicense, AnatomyProvenance, AnatomySource } from "./contracts/anatomy-foundation";

export const TOTALSEGMENTATOR_AUDIT_VERSION = "2.18.0@246be1de845148081a151870b99aaf8407b7621c";
const ts = "https://github.com/wasserth/TotalSegmentator/blob/246be1de845148081a151870b99aaf8407b7621c/";
export const ANATOMY_LICENSES: readonly AnatomyLicense[] = [
  {"id":"HEART_REFERENCE-license-unresolved","termsRefs":["https://sketchfab.com/3d-models/full-patient-heart-from-ct-with-texture-ae1c46e7f44547b3aea4d79acdb6e6ab"],"reviewStatus":"unresolved","commercialCompatibility":"unresolved","requiredAttribution":["APIL / apil_tgh","Advanced Perioperative Imaging Lab / Toronto Heart Atlas"],"derivativeObligations":["Resolve exact source license version, attribution and derivative/commercial obligations before use."]},
  {"id":"HEART_HERO-license-unresolved","termsRefs":["https://sketchfab.com/3d-models/anatomically-correct-human-heart-54fa880728d14c11afff78be8721620a"],"reviewStatus":"unresolved","commercialCompatibility":"unresolved","requiredAttribution":["Pigcraft / s8819296"],"derivativeObligations":["Resolve exact source license version, attribution and derivative/commercial obligations before use."]},
  {"id":"HEART_INTERNAL-license-unresolved","termsRefs":["https://sketchfab.com/3d-models/human-heart-internal-structure-3d-model-21d346f72230432e8ed5fe448b03cca5"],"reviewStatus":"unresolved","commercialCompatibility":"unresolved","requiredAttribution":["Haiqa Arif / ansarihaiqaarif"],"derivativeObligations":["Resolve exact source license version, attribution and derivative/commercial obligations before use."]},
  {"id":"HEART_CORONARY-license-unresolved","termsRefs":["https://sketchfab.com/3d-models/3d-digital-model-of-coronary-arteries-cb63e7714a574984835160530957748b"],"reviewStatus":"unresolved","commercialCompatibility":"unresolved","requiredAttribution":["Jeslyn Poo Hwee Ming / jeslynpoo","Department of Physiology, National University of Singapore (NUS)"],"derivativeObligations":["Resolve exact source license version, attribution and derivative/commercial obligations before use."]},
  {"id":"HEART_MOTION-license-unresolved","termsRefs":["https://sketchfab.com/3d-models/beating-heart-d9845afb1ee64ad094adc96320c67d98","https://creativecommons.org/licenses/by/4.0/"],"reviewStatus":"unresolved","commercialCompatibility":"unresolved","requiredAttribution":["jalmer","Original work: Dreamwasabducted"],"derivativeObligations":["Resolve exact source license version, attribution and derivative/commercial obligations before use."]},
  { id: "zenodo-4506463-CC-BY-4.0", termsRefs: ["https://zenodo.org/records/4506463", "https://creativecommons.org/licenses/by/4.0/"], reviewStatus: "terms-reviewed", commercialCompatibility: "permitted-with-obligations", requiredAttribution: ["Schuler, S. & Loewe, A. (2021). Biventricular statistical shape model of the human heart adapted for computer simulations (v2). Zenodo. https://doi.org/10.5281/zenodo.4506463. CC BY 4.0."], derivativeObligations: ["Retain attribution, link license and indicate changes; source identity verification is not anatomical or clinical approval."] },
  { id: "totalsegmentator-v1-unresolved", termsRefs: [ts + "LICENSE", "https://github.com/wasserth/TotalSegmentator/issues/618#issuecomment-5948385507"], reviewStatus: "unresolved", commercialCompatibility: "unresolved", requiredAttribution: ["TotalSegmentator and nnU-Net."], derivativeObligations: ["Code terms alone do not resolve the selected V1 model/data/output rights; inspect exact artifact before use."] },
  { id: "Apache-2.0", termsRefs: [ts + "LICENSE", ts + "README.md"], reviewStatus: "terms-reviewed", commercialCompatibility: "permitted-with-obligations", requiredAttribution: ["Retain applicable copyright, license and NOTICE; cite TotalSegmentator and nnU-Net as requested upstream."], derivativeObligations: ["Preserve notices and indicate changes; case-specific output provenance remains required."] },
  { id: "totalsegmentator-commercial-unresolved", termsRefs: [ts + "README.md", "https://backend.totalsegmentator.com/license-academic/"], reviewStatus: "unresolved", commercialCompatibility: "requires-license", requiredAttribution: ["TotalSegmentator and nnU-Net; additional agreement terms unresolved."], derivativeObligations: ["Acquire and review commercial model/output rights; an academic license is not commercial clearance."] },
  { id: "z-anatomy-mixed-terms", termsRefs: ["https://github.com/Z-Anatomy/Models-of-human-anatomy/blob/ad876c0af51563498816c6f0da4283ebd1914ffa/Readme.md", "https://creativecommons.org/licenses/by-sa/4.0/"], reviewStatus: "unresolved", commercialCompatibility: "unresolved", requiredAttribution: ["Z-Anatomy and BodyParts3D; asset-specific upstream contributors."], derivativeObligations: ["CC BY-SA 4.0 for atlas derivatives; listed inner-ear/kidney references include NC terms. Resolve component provenance and retopology obligations."] },
  { id: "CC-BY-4.0", termsRefs: ["https://dbarchive.biosciencedbc.jp/jp/bodyparts3d/lic.html", "https://creativecommons.org/licenses/by/4.0/"], reviewStatus: "terms-reviewed", commercialCompatibility: "permitted-with-obligations", requiredAttribution: ["BodyParts3D © Database Center for Life Science, licensed under CC BY 4.0."], derivativeObligations: ["Attribute, link license and indicate modifications; confirm the chosen archive/version is covered."] },
  { id: "CC-BY-SA-2.1-JP", termsRefs: ["https://lifesciencedb.jp/bp3d/info_en/license/index.html", "https://creativecommons.org/licenses/by-sa/2.1/jp/deed.en"], reviewStatus: "terms-reviewed", commercialCompatibility: "permitted-with-obligations", requiredAttribution: ["BodyParts3D © Database Center for Life Science."], derivativeObligations: ["ShareAlike and attribution; do not assume the later archive terms relicense Z-Anatomy derivatives."] },
  { id: "unresolved-development", termsRefs: ["medical-assets/LICENSE_MANIFEST.json"], reviewStatus: "unresolved", commercialCompatibility: "unresolved", requiredAttribution: [], derivativeObligations: ["Internal placeholder only; no distribution clearance."] },
];
export const ANATOMY_SOURCES: readonly AnatomySource[] = [
  {"id":"HEART_REFERENCE","sourceVersion":"sketchfab-ae1c46e7f44547b3aea4d79acdb6e6ab-revision-unresolved","canonicalName":"Full Patient Heart from CT - with texture","upstreamProject":"https://sketchfab.com/3d-models/full-patient-heart-from-ct-with-texture-ae1c46e7f44547b3aea4d79acdb6e6ab","licenseId":"HEART_REFERENCE-license-unresolved","evidenceRefs":["https://sketchfab.com/3d-models/full-patient-heart-from-ct-with-texture-ae1c46e7f44547b3aea4d79acdb6e6ab","medical-assets/LICENSE_MANIFEST.json"],"limitations":["Intended OrganHeal role: reference; not medical authority or clinical approval.","INTERNAL-REVIEW only; anatomicallyValidated=false; clinical approval=unreviewed; patient-facing=false; no geometry mixing.","Exact source revision, archive identity/hash and acquisition evidence unresolved. Public attribution/license metadata supplied by owner; asset-specific license clearance unresolved."]},
  {"id":"HEART_HERO","sourceVersion":"sketchfab-54fa880728d14c11afff78be8721620a-revision-unresolved","canonicalName":"Anatomically Correct Human Heart","upstreamProject":"https://sketchfab.com/3d-models/anatomically-correct-human-heart-54fa880728d14c11afff78be8721620a","licenseId":"HEART_HERO-license-unresolved","evidenceRefs":["https://sketchfab.com/3d-models/anatomically-correct-human-heart-54fa880728d14c11afff78be8721620a","medical-assets/LICENSE_MANIFEST.json"],"limitations":["Intended OrganHeal role: hero visual candidate; not medical authority or clinical approval.","INTERNAL-REVIEW only; anatomicallyValidated=false; clinical approval=unreviewed; patient-facing=false; no geometry mixing.","Exact source revision, archive identity/hash and acquisition evidence unresolved. Public attribution/license metadata supplied by owner; asset-specific license clearance unresolved."]},
  {"id":"HEART_INTERNAL","sourceVersion":"sketchfab-21d346f72230432e8ed5fe448b03cca5-revision-unresolved","canonicalName":"Human Heart Internal Structure 3D Model","upstreamProject":"https://sketchfab.com/3d-models/human-heart-internal-structure-3d-model-21d346f72230432e8ed5fe448b03cca5","licenseId":"HEART_INTERNAL-license-unresolved","evidenceRefs":["https://sketchfab.com/3d-models/human-heart-internal-structure-3d-model-21d346f72230432e8ed5fe448b03cca5","medical-assets/LICENSE_MANIFEST.json"],"limitations":["Intended OrganHeal role: internal/cutaway candidate; not medical authority or clinical approval.","INTERNAL-REVIEW only; anatomicallyValidated=false; clinical approval=unreviewed; patient-facing=false; no geometry mixing.","Exact source revision, archive identity/hash and acquisition evidence unresolved. Public attribution/license metadata supplied by owner; asset-specific license clearance unresolved."]},
  {"id":"HEART_CORONARY","sourceVersion":"sketchfab-cb63e7714a574984835160530957748b-revision-unresolved","canonicalName":"3D Digital Model of Coronary Arteries","upstreamProject":"https://sketchfab.com/3d-models/3d-digital-model-of-coronary-arteries-cb63e7714a574984835160530957748b","licenseId":"HEART_CORONARY-license-unresolved","evidenceRefs":["https://sketchfab.com/3d-models/3d-digital-model-of-coronary-arteries-cb63e7714a574984835160530957748b","medical-assets/LICENSE_MANIFEST.json"],"limitations":["Intended OrganHeal role: coronary candidate; not medical authority or clinical approval.","INTERNAL-REVIEW only; anatomicallyValidated=false; clinical approval=unreviewed; patient-facing=false; no geometry mixing.","Exact source revision, archive identity/hash and acquisition evidence unresolved. Public attribution/license metadata supplied by owner; asset-specific license clearance unresolved."]},
  {"id":"HEART_MOTION","sourceVersion":"sketchfab-d9845afb1ee64ad094adc96320c67d98-revision-unresolved","canonicalName":"Beating-heart","upstreamProject":"https://sketchfab.com/3d-models/beating-heart-d9845afb1ee64ad094adc96320c67d98","licenseId":"HEART_MOTION-license-unresolved","evidenceRefs":["https://sketchfab.com/3d-models/beating-heart-d9845afb1ee64ad094adc96320c67d98","medical-assets/LICENSE_MANIFEST.json"],"limitations":["Intended OrganHeal role: motion candidate; not medical authority or clinical approval.","INTERNAL-REVIEW only; anatomicallyValidated=false; clinical approval=unreviewed; patient-facing=false; no geometry mixing.","Exact source revision, archive identity/hash and acquisition evidence unresolved. Public attribution/license metadata supplied by owner; asset-specific license clearance unresolved."]},
  { id: "zenodo-4506463", sourceVersion: "v2", canonicalName: "Biventricular statistical shape model of the human heart adapted for computer simulations", upstreamProject: "https://zenodo.org/records/4506463", licenseId: "zenodo-4506463-CC-BY-4.0", evidenceRefs: ["https://zenodo.org/api/records/4506463", "https://doi.org/10.5281/zenodo.4506463", "medical-assets/LICENSE_MANIFEST.json"], limitations: ["INTERNAL-REVIEW candidate only; no runtime geometry imported or source profile activated. RV epicardium uses a source-generated fixed 3 mm wall thickness. No atrial myocardium or separately encoded septum; no anatomical or clinical approval."] },
  { id: "totalsegmentator-v1", sourceVersion: "v1-annotation-semantics-unresolved", canonicalName: "TotalSegmentator V1", upstreamProject: "https://github.com/wasserth/TotalSegmentator", licenseId: "totalsegmentator-v1-unresolved", evidenceRefs: ["https://github.com/wasserth/TotalSegmentator/issues/618#issuecomment-5948385507"], limitations: ["Maintainer cannot definitively resolve V1 cardiac label semantics; class 44 remains anatomy-conditional. V1 model/data terms not independently cleared."] },
  { id: "totalsegmentator-v2-total", sourceVersion: TOTALSEGMENTATOR_AUDIT_VERSION, canonicalName: "TotalSegmentator V2 total", upstreamProject: "https://github.com/wasserth/TotalSegmentator", licenseId: "Apache-2.0", evidenceRefs: [ts + "README.md", ts + "totalsegmentator/map_to_binary.py"], limitations: ["117 documented total labels are candidate segmentation categories, not asset-specific anatomical or clinical approval. Predictions require case-specific review."] },
  { id: "totalsegmentator-v2-heartchambers", sourceVersion: TOTALSEGMENTATOR_AUDIT_VERSION, canonicalName: "TotalSegmentator heartchambers_highres", upstreamProject: "https://github.com/wasserth/TotalSegmentator", licenseId: "totalsegmentator-commercial-unresolved", evidenceRefs: [ts + "resources/heartchambers_highres_details.md", ts + "totalsegmentator/map_tasks_config.py", ts + "totalsegmentator/map_to_binary.py"], limitations: ["Task 301, commercial=true; exact weight artifact/version not inspected. Chamber wall/cavity and complete myocardial regions unresolved; no named septum or valves in its seven-label map."] },
  { id: "z-anatomy-local-reference", sourceVersion: "local-reference-revision-unpinned", canonicalName: "Z-Anatomy local reference", upstreamProject: "https://github.com/Z-Anatomy/Models-of-human-anatomy", licenseId: "z-anatomy-mixed-terms", evidenceRefs: ["medical-assets/LICENSE_MANIFEST.json", "https://github.com/Z-Anatomy/Models-of-human-anatomy/blob/ad876c0af51563498816c6f0da4283ebd1914ffa/Readme.md"], limitations: ["Current atlas snapshot is audit evidence only; local Startup.blend revision is unknown. Retopology is not legal clearance or clinical verification."] },
  { id: "bodyparts3d-current-archive", sourceVersion: "archive-4.0-license-2025-02-27", canonicalName: "BodyParts3D current archive", upstreamProject: "https://dbarchive.biosciencedbc.jp/jp/bodyparts3d/", licenseId: "CC-BY-4.0", evidenceRefs: ["https://dbarchive.biosciencedbc.jp/data/bodyparts3d/LATEST/README_e.html", "https://dbarchive.biosciencedbc.jp/en/bodyparts3d/lic.html", "https://dbarchive.biosciencedbc.jp/en/bodyparts3d/download.html", "medical-assets/LICENSE_MANIFEST.json"], limitations: ["Current archive/license metadata only; no meshes imported or medically reviewed. Legacy site still declares BY-SA 2.1 JP."] },
  { id: "bodyparts3d-legacy-site", sourceVersion: "legacy-site-version-unresolved", canonicalName: "BodyParts3D legacy site", upstreamProject: "https://lifesciencedb.jp/bp3d/", licenseId: "CC-BY-SA-2.1-JP", evidenceRefs: ["https://lifesciencedb.jp/bp3d/info_en/license/index.html"], limitations: ["Resolve exact version/license chain for any legacy derivative; site and current archive differ."] },
  { id: "organheal-development", sourceVersion: "heart-v2-development", canonicalName: "OrganHeal internal illustrative geometry", upstreamProject: "render/blender/heart_builder.py", licenseId: "unresolved-development", evidenceRefs: ["render/blender/heart_builder.py"], limitations: ["Tubes/tori are engineering placeholders, not verified vessels or valves."] },
];

export function developmentAnatomyMetadata(placeholder: boolean): { provenance: AnatomyProvenance; assessment: AnatomyAssessment } {
  const source = ANATOMY_SOURCES.find(item => item.id === (placeholder ? "organheal-development" : "z-anatomy-local-reference"))!;
  return {
    provenance: { sourceId: source.id, sourceVersion: source.sourceVersion, licenseId: source.licenseId, evidenceRefs: source.evidenceRefs,
      derivation: placeholder ? "Illustrative primitive; no medical geometry claim." : "Reference-derived retopology/centerline; imported source revision unresolved.", licenseReview: { status: "unresolved", evidenceRefs: [] } },
    assessment: { geometryStatus: "imported", semanticStatus: "unverified", clinicalApprovalStatus: "unreviewed", renderCompatibility: "blender-compatible", geometryEvidenceRefs: [], semanticEvidenceRefs: [], clinicalEvidenceRefs: [] },
  };
}
