"use client";

import { useEffect, useState } from "react";
import Link from "next/link";

type Language = "en" | "ar";

function getStoredLanguage(): Language {
  if (typeof window === "undefined") return "en";

  const savedLanguage =
    localStorage.getItem("organheal-language") ||
    localStorage.getItem("organhealLanguage") ||
    localStorage.getItem("organheal_language") ||
    localStorage.getItem("language") ||
    "";

  return savedLanguage.toLowerCase().startsWith("ar") ? "ar" : "en";
}

export default function MedicalDisclaimerContent() {
  const [language, setLanguage] = useState<Language>("en");
  const isArabic = language === "ar";

  useEffect(() => {
    function syncLanguage() {
      const selectedLanguage = getStoredLanguage();

      setLanguage(selectedLanguage);
      document.documentElement.lang = selectedLanguage;
      document.documentElement.dir = selectedLanguage === "ar" ? "rtl" : "ltr";
    }

    syncLanguage();

    window.addEventListener("storage", syncLanguage);
    window.addEventListener("organheal-language-change", syncLanguage);

    return () => {
      window.removeEventListener("storage", syncLanguage);
      window.removeEventListener("organheal-language-change", syncLanguage);
    };
  }, []);

  function text(en: string, ar: string) {
    return isArabic ? ar : en;
  }

  const emergencySymptoms = [
    text("Severe chest pain", "ألم شديد في الصدر"),
    text("Severe shortness of breath", "ضيق نفس شديد"),
    text("Fainting or loss of consciousness", "إغماء أو فقدان وعي"),
    text("Stroke-like symptoms", "أعراض تشبه الجلطة"),
    text("Severe bleeding", "نزيف شديد"),
    text("Confusion or sudden weakness", "تشوش أو ضعف مفاجئ"),
  ];

  const disclaimerSections = [
    {
      title: text("1. Not a Medical Diagnosis", "1. ليس تشخيصًا طبيًا"),
      items: [
        text(
          "OrganHeal AI does not diagnose medical conditions, confirm diseases, prescribe medications, recommend treatment plans, or replace clinical judgment.",
          "OrganHeal AI لا يشخّص الحالات الطبية، ولا يؤكد الأمراض، ولا يصف الأدوية، ولا يوصي بخطط علاجية، ولا يستبدل الحكم السريري للطبيب."
        ),
        text(
          "Any result, score, summary, or explanation generated by the platform is educational and should be reviewed by a licensed healthcare professional.",
          "أي نتيجة أو درجة أو ملخص أو شرح تنتجه المنصة هو تعليمي ويجب مراجعته مع مختص صحي مرخص."
        ),
      ],
    },
    {
      title: text("2. Emergency Warning", "2. التحذير في حالات الطوارئ"),
      items: [
        text(
          "Do not use OrganHeal AI for emergencies or urgent medical decisions.",
          "لا تستخدم OrganHeal AI في الحالات الطارئة أو القرارات الطبية العاجلة."
        ),
        text(
          "If you have urgent or severe symptoms, seek emergency medical care immediately or contact local emergency services.",
          "إذا كانت لديك أعراض عاجلة أو شديدة، اطلب الرعاية الطبية الطارئة فورًا أو تواصل مع خدمات الطوارئ المحلية."
        ),
      ],
    },
    {
      title: text("3. Lab and Report Interpretation", "3. تفسير التحاليل والتقارير"),
      items: [
        text(
          "Lab values and medical reports can be complex and depend on age, medical history, medications, symptoms, pregnancy status, clinical examination, and other factors.",
          "قيم المختبر والتقارير الطبية قد تكون معقدة وتعتمد على العمر، التاريخ الصحي، الأدوية، الأعراض، الحمل، الفحص السريري، وعوامل أخرى."
        ),
        text(
          "OrganHeal summaries are designed to organize and explain information, not to replace professional interpretation.",
          "ملخصات OrganHeal مصممة لتنظيم وشرح المعلومات، وليس لاستبدال التفسير الطبي المهني."
        ),
      ],
    },
    {
      title: text("4. AI Limitations", "4. حدود الذكاء الاصطناعي"),
      items: [
        text(
          "AI-generated content may contain errors, miss important context, misunderstand uploaded information, or produce incomplete explanations.",
          "المحتوى الناتج عن الذكاء الاصطناعي قد يحتوي على أخطاء، أو قد يفوّت سياقًا مهمًا، أو يسيء فهم بعض المعلومات المرفوعة، أو ينتج شرحًا غير مكتمل."
        ),
        text(
          "Users should not rely on OrganHeal AI as the only source for health decisions.",
          "يجب ألا يعتمد المستخدم على OrganHeal AI كمصدر وحيد لاتخاذ القرارات الصحية."
        ),
      ],
    },
    {
      title: text("5. Professional Care", "5. الرعاية المهنية"),
      items: [
        text(
          "Always consult a licensed doctor or qualified healthcare professional for diagnosis, treatment, medication decisions, or urgent medical concerns.",
          "استشر دائمًا طبيبًا مرخصًا أو مختصًا صحيًا مؤهلًا للتشخيص، العلاج، قرارات الأدوية، أو أي مخاوف طبية عاجلة."
        ),
        text(
          "Do not stop, start, or change medications based only on OrganHeal AI outputs.",
          "لا توقف أو تبدأ أو تغيّر أي دواء بناءً فقط على مخرجات OrganHeal AI."
        ),
      ],
    },
    {
      title: text("6. User Responsibility", "6. مسؤولية المستخدم"),
      items: [
        text(
          "Users are responsible for reviewing information carefully and seeking appropriate professional care when needed.",
          "يتحمل المستخدم مسؤولية مراجعة المعلومات بعناية وطلب الرعاية المهنية المناسبة عند الحاجة."
        ),
        text(
          "Users should provide accurate information when using assessments, reports, check-ins, and health history features.",
          "يجب على المستخدم تقديم معلومات دقيقة عند استخدام التقييمات، التقارير، التحديثات الصحية، وميزات التاريخ الصحي."
        ),
      ],
    },
  ];

  const safetyCards = [
    {
      title: text("Educational only", "تعليمي فقط"),
      note: text(
        "Helps explain and organize health information.",
        "يساعد على شرح وتنظيم المعلومات الصحية."
      ),
    },
    {
      title: text("Not emergency care", "ليس للطوارئ"),
      note: text(
        "Urgent symptoms need immediate professional help.",
        "الأعراض العاجلة تحتاج مساعدة طبية فورية."
      ),
    },
    {
      title: text("Professional review", "مراجعة مختص"),
      note: text(
        "Important results should be reviewed clinically.",
        "النتائج المهمة يجب مراجعتها طبيًا."
      ),
    },
  ];

  return (
    <main className="ohPageShell" dir={isArabic ? "rtl" : "ltr"} lang={isArabic ? "ar" : "en"}>
      <div className="ohContainer ohStack large" style={{ padding: "32px 0 64px" }}>
        <section className="ohHero">
          <div className="ohHeroGrid">
            <div>
              <p className="ohEyebrow">
                {text("Medical Disclaimer", "إخلاء المسؤولية الطبية")}
              </p>

              <h1 className="ohTitle">
                {text(
                  "OrganHeal is educational. It does not replace medical care.",
                  "OrganHeal تعليمي ولا يستبدل الرعاية الطبية."
                )}
              </h1>

              <p className="ohLead">
                {text(
                  "OrganHeal AI provides educational and organizational health analysis only. It is not a substitute for professional medical advice, diagnosis, treatment, or emergency care.",
                  "OrganHeal AI يقدم معلومات صحية تعليمية وتنظيمية فقط. لا يُعد بديلًا عن الاستشارة الطبية المهنية أو التشخيص أو العلاج أو الرعاية الطارئة."
                )}
              </p>

              <div className="ohButtonRow" style={{ marginTop: "24px" }}>
                <Link href="/contact" className="primaryBtn">
                  {text("Contact", "تواصل معنا")}
                </Link>

                <Link href="/terms" className="secondaryBtn">
                  {text("Terms of Use", "شروط الاستخدام")}
                </Link>

                <Link href="/privacy" className="secondaryBtn">
                  {text("Privacy Policy", "سياسة الخصوصية")}
                </Link>
              </div>
            </div>

            <div className="ohCard">
              <div className="ohCardHeader">
                <div>
                  <p className="ohMetricLabel">
                    {text("Last Updated", "آخر تحديث")}
                  </p>

                  <h2 className="ohCardTitle" style={{ marginTop: "8px" }}>
                    {text("June 2026", "يونيو 2026")}
                  </h2>
                </div>

                <span className="ohStatusBadge risk">
                  {text("Important", "مهم")}
                </span>
              </div>

              <p className="ohCardText">
                {text(
                  "Use OrganHeal to prepare questions, understand reports, and organize your health journey. Do not use it as your only source for medical decisions.",
                  "استخدم OrganHeal لتحضير الأسئلة، فهم التقارير، وتنظيم رحلتك الصحية. لا تستخدمه كمصدر وحيد لاتخاذ قرارات طبية."
                )}
              </p>
            </div>
          </div>
        </section>

        <section className="ohGrid cols3">
          {safetyCards.map((card) => (
            <article className="ohMetricCard" key={card.title}>
              <span className="ohMetricLabel">{card.title}</span>
              <span className="ohMetricHint">{card.note}</span>
            </article>
          ))}
        </section>

        <section className="ohActionPanel">
          <div className="ohCardHeader" style={{ alignItems: "flex-start" }}>
            <div>
              <p className="ohMetricLabel">
                {text("Emergency warning", "تحذير الطوارئ")}
              </p>

              <h2 className="ohCardTitle" style={{ fontSize: "1.7rem" }}>
                {text(
                  "Do not use OrganHeal for urgent symptoms.",
                  "لا تستخدم OrganHeal للأعراض العاجلة."
                )}
              </h2>

              <p className="ohCardText">
                {text(
                  "If you have severe or urgent symptoms, seek emergency medical care immediately.",
                  "إذا كانت لديك أعراض شديدة أو عاجلة، اطلب الرعاية الطبية الطارئة فورًا."
                )}
              </p>
            </div>

            <span className="ohStatusBadge risk">
              {text("Emergency care first", "الطوارئ أولًا")}
            </span>
          </div>

          <div className="ohGrid cols3" style={{ marginTop: "20px" }}>
            {emergencySymptoms.map((symptom) => (
              <div className="ohMetricCard" key={symptom}>
                <span className="ohMetricLabel">{symptom}</span>
              </div>
            ))}
          </div>
        </section>

        <section className="ohStack">
          {disclaimerSections.map((section) => (
            <article className="ohCard" key={section.title}>
              <h2 className="ohCardTitle">{section.title}</h2>

              <div className="ohTimeline" style={{ marginTop: "18px" }}>
                {section.items.map((item) => (
                  <div className="ohTimelineItem" key={item}>
                    <span className="ohTimelineDot" />
                    <p className="ohTimelineMeta">{item}</p>
                  </div>
                ))}
              </div>
            </article>
          ))}
        </section>

        <section className="ohGrid cols2">
          <article className="ohActionPanel">
            <p className="ohMetricLabel">
              {text("Before making health decisions", "قبل اتخاذ قرارات صحية")}
            </p>

            <h2 className="ohCardTitle">
              {text(
                "Review important results with licensed professionals.",
                "راجع النتائج المهمة مع مختصين مرخصين."
              )}
            </h2>

            <p className="ohCardText">
              {text(
                "Bring OrganHeal summaries to your appointment as preparation material, not as a final medical conclusion.",
                "خذ ملخصات OrganHeal إلى موعدك كمواد تحضير، وليس كاستنتاج طبي نهائي."
              )}
            </p>

            <Link href="/doctor-portal" className="primaryBtn">
              {text("Open Doctor Portal", "فتح بوابة الطبيب")}
            </Link>
          </article>

          <article className="ohActionPanel">
            <p className="ohMetricLabel">
              {text("Related policies", "سياسات مرتبطة")}
            </p>

            <h2 className="ohCardTitle">
              {text(
                "Understand privacy and platform use rules.",
                "افهم قواعد الخصوصية واستخدام المنصة."
              )}
            </h2>

            <p className="ohCardText">
              {text(
                "The Privacy Policy and Terms of Use explain how OrganHeal handles information and how the platform should be used.",
                "توضح سياسة الخصوصية وشروط الاستخدام كيف يتعامل OrganHeal مع المعلومات وكيف يجب استخدام المنصة."
              )}
            </p>

            <div className="ohButtonRow">
              <Link href="/privacy" className="secondaryBtn">
                {text("Privacy", "الخصوصية")}
              </Link>

              <Link href="/terms" className="secondaryBtn">
                {text("Terms", "الشروط")}
              </Link>
            </div>
          </article>
        </section>

        <section className="ohTrustNotice">
          <span aria-hidden="true">🩺</span>
          <div>
            <strong>
              {text("Final safety note", "ملاحظة سلامة أخيرة")}
            </strong>
            <br />
            {text(
              "OrganHeal can support understanding, organization, and preparation, but licensed healthcare professionals remain responsible for diagnosis and treatment decisions.",
              "يمكن لـ OrganHeal دعم الفهم والتنظيم والتحضير، لكن المختصين الصحيين المرخصين هم المرجع في التشخيص وقرارات العلاج."
            )}
          </div>
        </section>
      </div>
    </main>
  );
}


