create table if not exists public.visit_notes (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users (id) on delete cascade,
  visit_date date not null default current_date,
  doctor_summary text not null
    check (char_length(doctor_summary) between 1 and 4000),
  medication_changes text
    check (medication_changes is null or char_length(medication_changes) <= 2000),
  follow_up_date date,
  created_at timestamptz not null default now()
);

create index if not exists visit_notes_user_visit_date_idx
  on public.visit_notes (user_id, visit_date desc, created_at desc);

alter table public.visit_notes enable row level security;

drop policy if exists "visit_notes_select_own" on public.visit_notes;
create policy "visit_notes_select_own"
  on public.visit_notes
  for select
  to authenticated
  using (auth.uid() = user_id);

drop policy if exists "visit_notes_insert_own" on public.visit_notes;
create policy "visit_notes_insert_own"
  on public.visit_notes
  for insert
  to authenticated
  with check (auth.uid() = user_id);

drop policy if exists "visit_notes_delete_own" on public.visit_notes;
create policy "visit_notes_delete_own"
  on public.visit_notes
  for delete
  to authenticated
  using (auth.uid() = user_id);
